# UE20CS343-tOPICS IN DEEP LEARNING
---

    Name    -Ayush Singh
    SRN     -PES2UG20CS081
    SECTION -6B

---


In [10]:

# task 1

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import warnings
warnings.filterwarnings("ignore")




a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
sum_graph = tf.add(a, b)


num1 = 8
num2 = 10



with tf.Session() as sess:
    sum_output = sess.run(sum_graph, feed_dict={
        a: num1,
        b: num2
        })

    print("The sum of {} and {} is {}".format(num1, num2, sum_output))


sess = tf.Session()

print(sess.run(sum_graph, feed_dict={a:num1, b:num2}))
sess.close()






The sum of 8 and 10 is 18
18


In [11]:
#task 2

from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import warnings
warnings.filterwarnings("ignore")


node1 = tf.constant(18)
node2 = tf.constant(2)
node3 = tf.placeholder(dtype=tf.int32)
node4 = tf.constant(10)
node5 = tf.placeholder(dtype=tf.int32)
node6 = tf.multiply(node2, node3)
node7 = tf.multiply(node4, node5)
node8 = tf.add(node6, node7)
node9 = tf.add(node1,node8)
node10 = tf.constant(2)
node11 = tf.multiply(node10, node9)


#Ask for inputs
x = int(input("Please enter an integer"))
y = int(input("Please enter an integer"))

#Get ready to run
sess = tf.Session()

print(sess.run(node11, feed_dict={node3:x, node5:y}))
sess.close()

148


In [12]:
#task3

# Lets first import tensorflow and numpy
# use import tensorflow as tf if you are using version==1.14 or you could used
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np


a = np.zeros((2,2)) 
print(a.shape) # 2,2 array
b = np.zeros((3,1)) # 3,1 array
print(b.shape)

print(a)
print(b)

#Now lets us repeat the same in tensorflow
ta = tf.zeros((2,2)); tb = tf.ones((2,2))
print(ta)
print(a)

sess = tf.Session()
print(sess.run(ta))

a=tf.constant(18,name="a")
b=tf.constant(2,name="b")
c=tf.add(a,b,name="c")
print(c)


sess = tf.Session()
print(sess.run(c))

d=c+5
sess = tf.Session()
print(sess.run(c))
sess = tf.Session()
print(sess.run(d))


 

 

(2, 2)
(3, 1)
[[0. 0.]
 [0. 0.]]
[[0.]
 [0.]
 [0.]]
Tensor("zeros_3:0", shape=(2, 2), dtype=float32)
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
Tensor("c_3:0", shape=(), dtype=int32)
20
20
25


In [13]:
#task 4

from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import warnings
warnings.filterwarnings("ignore")

# %%
mat1 = tf.constant([1,2,3,4,5,6], shape=[3,2])
mat2 = tf.constant([8,7,9,7], shape=[2,2])

op = tf.matmul(mat1,mat2)

# %%
sess=tf.Session()
print(sess.run(op))


# %%





[[26 21]
 [60 49]
 [94 77]]


In [14]:
#task 5
import numpy as np

class NeuralNetwork():
    
    def __init__(self):
        # seeding for random number generation
        np.random.seed(1)
        
        #converting weights to a 3 by 1 matrix with values from -1 to 1 and mean of 0
        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1

    def sigmoid(self, x):
        #applying the sigmoid function
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        #computing derivative to the Sigmoid function
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):
        
        #training the model to make accurate predictions while adjusting weights continually
        for iteration in range(training_iterations):
            #siphon the training data via  the neuron
            output = self.think(training_inputs)

#computing error rate for back-propagation
            error = training_outputs - output
            
            #performing weight adjustments
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))

            self.synaptic_weights += adjustments

    def think(self, inputs):
        #passing the inputs via the neuron to get output   
        #converting values to floats
        
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output


if __name__ == "__main__":

    #initializing the neuron class
    neural_network = NeuralNetwork()

    print("Beginning Randomly Generated Weights: ")
    print(neural_network.synaptic_weights)

    #training data consisting of 4 examples--3 input values and 1 output
    training_inputs = np.array([[0,0,1],
                                [1,1,1],
                                [1,0,1],
                                [0,1,1]])

    training_outputs = np.array([[0,1,1,0]]).T

#training taking place
    neural_network.train(training_inputs, training_outputs, 15000)

    print("Ending Weights After Training: ")
    print(neural_network.synaptic_weights)

    user_input_one = str(input("User Input One: "))
    user_input_two = str(input("User Input Two: "))
    user_input_three = str(input("User Input Three: "))
    
    print("Considering New Situation: ", user_input_one, user_input_two, user_input_three)
    print("New Output data: ")
    print(neural_network.think(np.array([user_input_one, user_input_two, user_input_three])))
    print("Wow, we did it!")

# %%


# %%





Beginning Randomly Generated Weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Ending Weights After Training: 
[[10.08740896]
 [-0.20695366]
 [-4.83757835]]
Considering New Situation:  18 2 17
New Output data: 
[1.]
Wow, we did it!
